name: build
permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: false
          python-version: "3.13"
      - name: Install cli tools
        run: |
          uv tool install phosphorus
          uv tool install yamk
      - name: Build the project
        run: |
          cd python
          yam -e build
  build-rust:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: false
          python-version: "3.13"
      - name: Install stable rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt
      - name: Install cli tools
        run: |
          uv tool install yamk
      - name: Build the project
        run: |
          cd rust
          rustup default stable
          yam -e build
