name: lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-python:
    runs-on: ubuntu-latest
    container:
      image: spapanik/euler-py:2.0.0
      options: --user root
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Use cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/venv-lint
          key: venv-lint-${{ hashFiles('pyproject.toml') }}
      - name: Install dependencies
        run: |
          cd python
          python -m venv ~/.cache/venv-lint
          . ~/.cache/venv-lint/bin/activate
          yam install -g main -g lint -g test
      - name: Lint the project
        run: |
          cd python
          . ~/.cache/venv-lint/bin/activate
          yam -e lint
  lint-rust:
    runs-on: ubuntu-latest
    container:
      image: spapanik/euler-rust:2.0.0
      options: --user root
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          cd rust
          rustup default stable
          yam install
      - name: Lint the project
        run: |
          cd rust
          rustup default stable
          yam -e lint
