name: lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-python:
    runs-on: ubuntu-latest
    container:
      image: spapanik/euler-py:2.0.0
      options: --user root
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Create and activate a virtual environment
        run: |
          uv venv .venv
          echo "VIRTUAL_ENV=.venv" >> $GITHUB_ENV
          echo "$PWD/.venv/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          cd python
          yam install -g main -g lint -g test
      - name: Lint the project
        run: |
          cd python
          yam -e lint
  lint-rust:
    runs-on: ubuntu-latest
    container:
      image: spapanik/euler-rust:2.0.0
      options: --user root
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          cd rust
          rustup default stable
          yam install
      - name: Lint the project
        run: |
          cd rust
          rustup default stable
          yam -e lint
